In [1]:
import sqlite3
from pprint import pprint
conn = sqlite3.connect("AQI.db")
with conn:
    cursor = conn.cursor()        
    sql = '''
    SELECT date,aqi,pm25
    FROM records
    WHERE sitename = '大城'; 
    '''
    cursor.execute(sql)
    data_list = []
    for item in cursor.fetchall():
        date = item[0]
        aqi = item[1]
        pm25 = item[2]
        data_list.append({'date':date,'aqi':aqi,'pm25':pm25})

pprint(data_list)

[{'aqi': 67, 'date': '2024-11-04 05:00', 'pm25': 25},
 {'aqi': 68, 'date': '2024-11-04 06:00', 'pm25': 20},
 {'aqi': 67, 'date': '2024-11-04 07:00', 'pm25': 23},
 {'aqi': 65, 'date': '2024-11-04 08:00', 'pm25': 19},
 {'aqi': 64, 'date': '2024-11-04 09:00', 'pm25': 21},
 {'aqi': 63, 'date': '2024-11-04 10:00', 'pm25': 17},
 {'aqi': 58, 'date': '2024-11-04 11:00', 'pm25': 11},
 {'aqi': 55, 'date': '2024-11-04 12:00', 'pm25': 11},
 {'aqi': 53, 'date': '2024-11-04 13:00', 'pm25': 16},
 {'aqi': 51, 'date': '2024-11-04 14:00', 'pm25': 12},
 {'aqi': 49, 'date': '2024-11-04 15:00', 'pm25': 11},
 {'aqi': 45, 'date': '2024-11-04 16:00', 'pm25': 6},
 {'aqi': 39, 'date': '2024-11-05 03:00', 'pm25': 11},
 {'aqi': 37, 'date': '2024-11-05 04:00', 'pm25': 8},
 {'aqi': 38, 'date': '2024-11-05 05:00', 'pm25': 13},
 {'aqi': 39, 'date': '2024-11-05 06:00', 'pm25': 12},
 {'aqi': 40, 'date': '2024-11-05 07:00', 'pm25': 14},
 {'aqi': 43, 'date': '2024-11-05 08:00', 'pm25': 17},
 {'aqi': 42, 'date': '2024-11-05 09:00', 'pm25': 12},
 {'aqi': 46, 'date': '2024-11-05 10:00', 'pm25': 19},
 {'aqi': 46, 'date': '2024-11-05 11:00', 'pm25': 15},
 {'aqi': 46, 'date': '2024-11-05 12:00', 'pm25': 0},
 {'aqi': 53, 'date': '2024-11-05 13:00', 'pm25': 22},
 {'aqi': 54, 'date': '2024-11-05 14:00', 'pm25': 20},
 {'aqi': 57, 'date': '2024-11-05 15:00', 'pm25': 20}]

In [3]:
import pandas as pd
df = pd.DataFrame(data_list)
df['date'] = pd.to_datetime(df['date'])
df1 = df.set_index('date')
df1

                     aqi  pm25
date
2024-11-04 05:00:00   67    25
2024-11-04 06:00:00   68    20
2024-11-04 07:00:00   67    23
2024-11-04 08:00:00   65    19
2024-11-04 09:00:00   64    21
2024-11-04 10:00:00   63    17
2024-11-04 11:00:00   58    11
2024-11-04 12:00:00   55    11
2024-11-04 13:00:00   53    16
2024-11-04 14:00:00   51    12
2024-11-04 15:00:00   49    11
2024-11-04 16:00:00   45     6
2024-11-05 03:00:00   39    11
2024-11-05 04:00:00   37     8
2024-11-05 05:00:00   38    13
2024-11-05 06:00:00   39    12
2024-11-05 07:00:00   40    14
2024-11-05 08:00:00   43    17
2024-11-05 09:00:00   42    12
2024-11-05 10:00:00   46    19
2024-11-05 11:00:00   46    15
2024-11-05 12:00:00   46     0
2024-11-05 13:00:00   53    22
2024-11-05 14:00:00   54    20
2024-11-05 15:00:00   57    20

In [6]:
df1.plot()

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.